#!/usr/bin/env python3
"""Fetch self-hosted webfont files (build-time only) and emit local @font-face CSS.

Downloads the woff2 files Google Fonts serves for the chosen families/weights and
rewrites the CSS to point at assets/fonts/, so nothing is fetched from a CDN at
runtime. Keeps only the subsets we need to bound file size.
"""
import re
import subprocess
import sys
from pathlib import Path

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
KEEP_SUBSETS = {"latin", "latin-ext", "greek", "greek-ext"}
FONTS = {
    "Inter": "ital,wght@0,400;0,500;0,600;0,700;1,400",
    "Spectral": "ital,wght@0,400;0,600;0,700;1,400",
}
ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "assets" / "fonts"
CSS_OUT = ROOT / "assets" / "css" / "fonts.css"


def curl(url, binary=False):
    r = subprocess.run(["curl", "-sSL", "-A", UA, url], capture_output=True)
    r.check_returncode()
    return r.stdout if binary else r.stdout.decode("utf-8")


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    blocks_out, downloaded = [], {}
    for family, axis in FONTS.items():
        url = f"https://fonts.googleapis.com/css2?family={family}:{axis}&display=swap"
        css = curl(url)
        # Split into "/* subset */\n@font-face{...}" units
        for m in re.finditer(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
            subset, block = m.group(1), m.group(2)
            if subset not in KEEP_SUBSETS:
                continue
            fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
            style = re.search(r"font-style:\s*(\w+)", block).group(1)
            weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
            src = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            slug = fam.lower().replace(" ", "-")
            suffix = "-italic" if style == "italic" else ""
            fname = f"{slug}-{weight}{suffix}.{subset}.woff2"
            if fname not in downloaded:
                (FONT_DIR / fname).write_bytes(curl(src, binary=True))
                downloaded[fname] = True
            block = block.replace(src, f"/assets/fonts/{fname}")
            block = block.replace("url(", "url(", 1)
            blocks_out.append(f"/* {fam} {weight} {style} — {subset} */\n{block}")
    header = (
        "/* Self-hosted webfonts, generated by tools/fetch_fonts.py.\n"
        "   Inter © The Inter Project Authors · Spectral © The Spectral Project Authors.\n"
        "   Both under the SIL Open Font License 1.1 — full text in\n"
        "   assets/fonts/Inter-OFL.txt and assets/fonts/Spectral-OFL.txt. */\n\n"
    )
    CSS_OUT.write_text(header + "\n".join(blocks_out) + "\n", encoding="utf-8")
    print(f"downloaded {len(downloaded)} woff2 files -> {FONT_DIR}")
    print(f"wrote {CSS_OUT} ({len(blocks_out)} @font-face rules)")


if __name__ == "__main__":
    main()
